train: C:/Users/rohit/OneDrive/Desktop/Projects_main/potholeDetection/data/images/train
val: C:/Users/rohit/OneDrive/Desktop/Projects_main/potholeDetection/data/images/val

"split_ratio": 0.2 # default test train split ratio

"nc": 1 # number of classes (pothole = 1)
"names": ["pothole"]

n_epochs: 1
n_batch: 4
n_img_size: 480
custom_model_dir: "outputs/runs"
